=== leigient/549n_SGDS/Schema/EnumDefine.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://leigient.549n.com/EnumDefine"
	elementFormDefault ="qualified"
	attributeFormDefault ="qualified"
	xmlns="http://leigient.549n.com/EnumDefine"
	version="1.0">

<xs:annotation>
	<xs:appinfo>Common Enum Type Define</xs:appinfo>
	<xs:documentation>Common Enum Type Define Version 1.0</xs:documentation>
</xs:annotation>

<!-- Initial Enumeration Define -->

<!-- Initial Enumeration Define End -->

<xs:complexType name="EnumType">
	<xs:attribute name="ID" type="xs:string" use="required"/>
	<xs:attribute name="Value" type="xs:string" use="optional"/>
	<xs:attribute name="MappingData" type="xs:string" use="optional"/>
	<xs:attribute name="Comment" type="xs:string" use="optional"/>
	<xs:attribute name="UMETA" type="xs:string" use="optional"/>
</xs:complexType>

<xs:element name="EnumDefine">
<xs:complexType>

<xs:sequence>
	<xs:element name="EnumCategory"  minOccurs="1" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EnumData" type="EnumType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="EnumName" type="xs:string" use="required"/>
			<xs:attribute name="IDRangeMin" type="xs:int" use="required"/> <!-- Enum ID range min -->
			<xs:attribute name="IDRangeMax" type="xs:int" use="optional"/> <!-- Enum ID range max -->
			<xs:attribute name="Comment" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:sequence>

<xs:attribute name="Namespace" type="xs:string" use="required"/>		
<xs:attribute name="Version" type="xs:unsignedInt" use="required"/>		
<xs:attribute name="Comment" type="xs:string" use="required"/>			
	
</xs:complexType>
</xs:element>

</xs:schema>

=== leigient/549n_SGDS/Enum/SampleEnumType.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<e:EnumDefine xmlns:e="http://leigient.549n.com/EnumDefine"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://leigient.549n.com/EnumDefine.xsd ../Schema/EnumDefine.xsd"
 e:Namespace="CommonEnum" e:Version="1" e:Comment="common enum defines for 549n Project.">

<!-- Enum Category -->
<e:EnumCategory e:EnumName="SampleGenderType" e:IDRangeMin="0" e:Comment="성별" >
  <e:EnumData e:ID="Male" e:Comment="남성" />
  <e:EnumData e:ID="Female" e:Comment="여성" />
  <e:EnumData e:ID="Neutral" e:Comment="중성" />
</e:EnumCategory>

<e:EnumCategory e:EnumName="SampleElementType" e:IDRangeMin="0" e:Comment="속성" >
  <e:EnumData e:ID="Earth" e:Comment="지" />
  <e:EnumData e:ID="Water" e:Comment="수" />
  <e:EnumData e:ID="Fire" e:Comment="화" />
  <e:EnumData e:ID="Wind" e:Comment="풍" />
</e:EnumCategory>

<e:EnumCategory e:EnumName="SampleJobClassType" e:IDRangeMin="0" e:Comment="직업 클래스" >
  <e:EnumData e:ID="Knight" e:Comment="기사" />
  <e:EnumData e:ID="MagicUser" e:Comment="마법사" />
  <e:EnumData e:ID="Cleric" e:Comment="성직자" />
  <e:EnumData e:ID="Thief" e:Comment="도둑" />
</e:EnumCategory>

</e:EnumDefine>
